int64 scene_id
ValidatedGrasp[] candidates
CollisionBox[] dynamic_obstacles
---
bool success
string failure_reason

int32 selected_candidate_id

moveit_msgs/RobotTrajectory to_pre_grasp
moveit_msgs/RobotTrajectory approach

float32 planning_time
float32 cartesian_fraction
