frame_id: base_link

workspace:
  x_min: -0.27
  x_max: 1.5
  y_min: -0.60
  y_max: 1.0
  z_min: 0.0
  z_max: 2.0

collision_objects:
  - id: shelf_floor
    center: [0.57, -0.48, 0.00]
    size: [1.01, 0.305, 0.01]

  - id: shelf_back
    center: [0.57, -0.48, 0.24]
    size: [1.01, 0.305, 0.01]

  - id: shelf_left
    center: [-0.04, -0.47, 0.12]
    size: [0.50, 0.02, 0.24]

  - id: shelf_right
    center: [0.92, -0.47, 0.12]
    size: [0.50, 0.02, 0.24]
